title: José Javier Vázquez Rapp
logo: /assets/J10.jpg
description: AI enthusiastdriven to leverage my talents and expertise to make a positive impact on sustainability.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
