title: José Javier Vázquez Rapp
logo: /assets/J10.jpg
description: AI enthusiast driven to leverage my talents and expertise to make a positive impact on sustainability.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
